### ISSUE TITLE
form.reset() appears to reset form, but value remains

### ISSUE THREAD

**Issue by hawkett** [PolymerElements/gold-cc-expiration-input#22]
When calling form.reset(), form fields are all visibly cleared, but the actual value of the gold-cc-expiration-input is not.

Related to #23.

**Comment by notwaldorf** [comment]
I can't repro this anymore: http://jsbin.com/xivusa/edit?html,output
There were some fixes recently in `iron-form` that might have fixed this. Please let me know if you can still repro this, and we'll reopen the issue.
