### ISSUE TITLE
Tests seem to fail under shadow dom

### ISSUE THREAD

**Issue by rictic** [PolymerElements/gold-cc-expiration-input#34]
Here's the PR that turns on shadow dom: https://github.com/PolymerElements/gold-cc-expiration-input/pull/33

**Comment by rictic** [comment]
Looks like it's just from using `elem.querySelector` in the tests in a couple places.

**Comment by rictic** [comment]
There's still a focus-related issue that I didn't track down.

**Comment by notwaldorf** [comment]
This seems green on master now.
