### ISSUE TITLE
slash key should move input to year field

### ISSUE THREAD

**Issue by austingreco** [PolymerElements/gold-cc-expiration-input#36]
When filling out an expiration date it would be nice if typing `1/16` would work just like `1` <kbd>Tab</kbd> `16`

**Comment by notwaldorf** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved.

**Comment by austingreco** [comment]
I'm not sure if this is the right way to do this (using iron-a11y-keys). Let me know if there's a better way.

Also attempted to write a test for this but ran into this issue: https://github.com/PolymerElements/iron-test-helpers/issues/33
