### ISSUE TITLE
Same placeholder is used for year and month fields

### ISSUE THREAD

**Issue by ellenaua** [PolymerElements/gold-cc-expiration-input#47]
It would be great to specify "YY" placeholder for year field, and "MM" for month field.
But currently the same one placeholder is used for both 
https://github.com/PolymerElements/gold-cc-expiration-input/blob/master/date-input.html#L72
https://github.com/PolymerElements/gold-cc-expiration-input/blob/master/date-input.html#L90

**Comment by samuelli** [comment]
Looks like the default placeholders are actually broken (meant to be MM/YY)

**Comment by samuelli** [comment]
Proposing we just kill:
https://github.com/PolymerElements/gold-cc-expiration-input/blob/master/date-input.html#L72
https://github.com/PolymerElements/gold-cc-expiration-input/blob/master/date-input.html#L90

**Comment by notwaldorf** [comment]
@samuelli oooo yeah, that makes sense.
