### ISSUE TITLE
Input value is not actual

### ISSUE THREAD

**Issue by ellenaua** [PolymerElements/gold-cc-expiration-input#53]
### Description

Check this jsbin https://jsbin.com/ginujab/edit?html,output
At the beginning input has a value "02/24"
When I erase "4" value becomes "02/2"
When I erase last digit - "2" - input value does not change and remains "02/2" 
Even if I delete everything from input, value remains "02/2"
It happens because of this condition in the code https://github.com/PolymerElements/gold-cc-expiration-input/blob/master/gold-cc-expiration-input.html#L151
### Expected outcome

As a developer, when user deletes some digits, I want to get actual value which is in the input, even if value is invalid.
### Actual outcome

When user deletes some digits, I get some strange non-actual and invalid value "02/2" even if there's nothing in inputs or only "0" or "02"..
### Live Demo

https://jsbin.com/ginujab/edit?html,output
### Steps to reproduce

Check this jsbin https://jsbin.com/ginujab/edit?html,output
At the beginning input has a value "02/24"
Erase "4" - value will become "02/2"
Erase last digit - "2" - input value will not change and will remain "02/2" 
Even if you delete everything from input, value remains "02/2"
### Browsers Affected

- [x] Chrome
- [x] Firefox
- [x] Safari 9
- [x] Safari 8
- [x] Safari 7
- [x] Edge
- [x] IE 11
- [x] IE 10

**Comment by notwaldorf** [comment]
Ah yeah, that's totally a bug. Would you like to submit a PR (with a matching test) to fix this? 🍰

**Comment by ellenaua** [comment]
@notwaldorf submitted, please check https://github.com/PolymerElements/gold-cc-expiration-input/pull/54

**Comment by andrew-silva-movile** [comment]
Hi @notwaldorf, could you help us with a PR about this problem?
As #54 was closed I created a new one (#58) with all fixes (without TODOs) :smile:

Thanks again! o/

**Comment by andrew-silva-movile** [comment]
Hi @notwaldorf, thanks a lot for your help.
I'm already using v1.1.3 in production!

I see that we could close this issue with the bug fixed #58 

Do you agree? :smiley:

**Comment by notwaldorf** [comment]
@andrew-silva-movile Yup! P.S., next time if you add "fixes #53" to the PR description, it will automatically close the issue as well :)

**Comment by andrew-silva-movile** [comment]
@notwaldorf you right! Thanks again!
