### ISSUE TITLE
Polymer 2?

### ISSUE THREAD

**Issue by arkihillel** [PolymerElements/gold-cc-expiration-input#61]
Has this element (or all the Gold elements for that concern) been deprecated?
If not will they be upgraded to Polymer 2?
I don't see any branch letting me suppose so at the moment

**Comment by cgriffin4** [comment]
I, too, would like to know the status and roadmap for Gold Elements

**Comment by juanmendez92** [comment]
It's November 2017 and anything?

**Comment by notwaldorf** [comment]
OH! We completely missed this element! It wasn't on the tracking spreadsheet, and I think it just got missed out in the update! Really sorry about that.

@e111077 do you want to take a look at this, since you did the other gold elements? If not, I can take a look

**Comment by e111077** [comment]
Oops; on it

**Comment by SeanGrind** [comment]
What's the status of this?  I see two open pull requests from early December.
